name: lms-dev

services:
  api:
    container_name: lms_api_dev
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    env_file:
      - ./apps/api/.env.local
    ports:
      - "3001:3001"
    volumes:
      - ./apps/api/src:/app/src
      - ./apps/api/uploads:/app/uploads
      - /app/node_modules
    networks:
      - lms_network
    command: npm run start:dev
    restart: unless-stopped

  web:
    container_name: lms_web_dev
    build:
      context: ./apps/web
      dockerfile: Dockerfile
      target: development
    env_file:
      - ./apps/web/.env.local
    environment:
      - NEXT_PUBLIC_API_URL=http://api:3001
    ports:
      - "3000:3000"
    volumes:
      - ./apps/web:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - api
    networks:
      - lms_network
    command: npm run dev
    restart: unless-stopped

networks:
  lms_network:
    driver: bridge
